# Generated by Django 4.2.4 on 2023-10-17 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('tscNo', models.BigIntegerField(null=True, unique=True)),
                ('phoneNo', models.BigIntegerField(null=True)),
                ('profile_photo', models.ImageField(default='media/default.png', null=True, upload_to='media/profiles')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('learningAreas', models.ManyToManyField(blank=True, to='school_info.learningarea')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_learning_outcomes', models.TextField(max_length=500)),
                ('learning_experiences', models.TextField(max_length=500)),
                ('key_inquiry_question', models.TextField(max_length=500)),
                ('resources', models.TextField(max_length=100)),
                ('steps', models.TextField(max_length=1000)),
                ('extended_activity', models.TextField(max_length=500)),
                ('conclusion', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=300)),
                ('head_name', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemesOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=100)),
                ('specific_learning_outcomes', models.TextField(max_length=500)),
                ('learning_experiences', models.TextField(max_length=500)),
                ('key_inquiry_question', models.TextField(max_length=500)),
                ('resources', models.TextField(max_length=100)),
                ('assesment', models.CharField(max_length=200)),
                ('reflection', models.TextField(max_length=200)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.strand')),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.sub_strand')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordOfWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workdone', models.TextField(max_length=500)),
                ('reflection', models.TextField(max_length=500)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.lessonplan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.schemesofwork'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.strand'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='sub_strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.sub_strand'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
