# Generated by Django 4.2.4 on 2023-10-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tscNo',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
