# Generated by Django 4.2.4 on 2023-10-17 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PP1', 'PP 1'), ('PP2', 'PP 2'), ('Grade1', 'Grade 1'), ('Grade2', 'Grade 2'), ('Grade3', 'Grade 3'), ('Grade4', 'Grade 4'), ('Grade5', 'Grade 5'), ('Grade6', 'Grade 6'), ('Grade7', 'Grade 7'), ('Grade8', 'Grade 8'), ('Grade9', 'Grade 9')], max_length=1100)),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 11, 50, 332517, tzinfo=datetime.timezone.utc))),
                ('task', models.CharField(max_length=200)),
                ('max_score', models.IntegerField()),
                ('score', models.IntegerField()),
                ('remark', models.CharField(choices=[('Above Expectations', 'Above Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Approaching Expectations', 'Approaching Expectations'), ('Below Expectations', 'Below Expectations')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuthenticAssessmentRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term1', '1'), ('Term2', '2'), ('Term3', '3')], max_length=100)),
                ('year', models.CharField(choices=[('2023', '2023')], max_length=100)),
                ('task', models.CharField(max_length=150)),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 11, 50, 341511, tzinfo=datetime.timezone.utc))),
                ('criteria', models.TextField(max_length=500)),
                ('exceeds_expectations', models.TextField(max_length=500)),
                ('meets_expectations', models.TextField(max_length=500)),
                ('approaches_expectations', models.TextField(max_length=500)),
                ('below_expectations', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassActivitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PP1', 'PP 1'), ('PP2', 'PP 2'), ('Grade1', 'Grade 1'), ('Grade2', 'Grade 2'), ('Grade3', 'Grade 3'), ('Grade4', 'Grade 4'), ('Grade5', 'Grade 5'), ('Grade6', 'Grade 6'), ('Grade7', 'Grade 7'), ('Grade8', 'Grade 8'), ('Grade9', 'Grade 9')], max_length=100)),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 11, 50, 328519, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('admissionNo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('home_address', models.CharField(max_length=100)),
                ('parent_or_guardian', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('year_joined', models.DateField()),
                ('picture', models.ImageField(default='media/default.png', null=True, upload_to='media/leaners')),
            ],
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PP1', 'PP 1'), ('PP2', 'PP 2'), ('Grade1', 'Grade 1'), ('Grade2', 'Grade 2'), ('Grade3', 'Grade 3'), ('Grade4', 'Grade 4'), ('Grade5', 'Grade 5'), ('Grade6', 'Grade 6'), ('Grade7', 'Grade 7'), ('Grade8', 'Grade 8'), ('Grade9', 'Grade 9')], max_length=101)),
                ('learningArea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PP1', 'PP 1'), ('PP2', 'PP 2'), ('Grade1', 'Grade 1'), ('Grade2', 'Grade 2'), ('Grade3', 'Grade 3'), ('Grade4', 'Grade 4'), ('Grade5', 'Grade 5'), ('Grade6', 'Grade 6'), ('Grade7', 'Grade 7'), ('Grade8', 'Grade 8'), ('Grade9', 'Grade 9')], max_length=100)),
                ('term', models.CharField(choices=[('Term1', '1'), ('Term2', '2'), ('Term3', '3')], max_length=100)),
                ('year', models.CharField(choices=[('2023', '2023')], max_length=10000)),
                ('portfolio', models.FileField(upload_to='media/portfolios')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term1', '1'), ('Term2', '2'), ('Term3', '3')], max_length=100)),
                ('year', models.CharField(choices=[('2023', '2023')], max_length=100)),
                ('skills_tested', models.TextField(max_length=500)),
                ('values_to_be_learned', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subStrand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SummativeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PP1', 'PP 1'), ('PP2', 'PP 2'), ('Grade1', 'Grade 1'), ('Grade2', 'Grade 2'), ('Grade3', 'Grade 3'), ('Grade4', 'Grade 4'), ('Grade5', 'Grade 5'), ('Grade6', 'Grade 6'), ('Grade7', 'Grade 7'), ('Grade8', 'Grade 8'), ('Grade9', 'Grade 9')], max_length=100)),
                ('term', models.CharField(choices=[('Term1', '1'), ('Term2', '2'), ('Term3', '3')], max_length=100)),
                ('year', models.CharField(choices=[('2023', '2023')], max_length=10000)),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 11, 50, 335513, tzinfo=datetime.timezone.utc))),
                ('max_score', models.IntegerField()),
                ('score', models.IntegerField()),
                ('remark', models.CharField(choices=[('Above Expectations', 'Above Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Approaching Expectations', 'Approaching Expectations'), ('Below Expectations', 'Below Expectations')], max_length=200)),
                ('classteacher_remark', models.TextField(max_length=200)),
                ('headteacher_remark', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SummativeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TermDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WrittenTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PP1', 'PP 1'), ('PP2', 'PP 2'), ('Grade1', 'Grade 1'), ('Grade2', 'Grade 2'), ('Grade3', 'Grade 3'), ('Grade4', 'Grade 4'), ('Grade5', 'Grade 5'), ('Grade6', 'Grade 6'), ('Grade7', 'Grade 7'), ('Grade8', 'Grade 8'), ('Grade9', 'Grade 9')], max_length=100)),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 11, 50, 334516, tzinfo=datetime.timezone.utc))),
                ('max_score', models.IntegerField()),
                ('score', models.IntegerField()),
                ('remark', models.CharField(choices=[('Above Expectations', 'Above Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Approaching Expectations', 'Approaching Expectations'), ('Below Expectations', 'Below Expectations')], max_length=100)),
                ('learning_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea')),
                ('strand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.strand')),
            ],
        ),
    ]
