# Generated by Django 4.2.4 on 2023-10-17 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtentest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summativeassessment',
            name='learning_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea'),
        ),
        migrations.AddField(
            model_name='summativeassessment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.summativetype'),
        ),
        migrations.AddField(
            model_name='sub_strand',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.strand'),
        ),
        migrations.AddField(
            model_name='strand',
            name='learningArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea'),
        ),
        migrations.AddField(
            model_name='projectrubric',
            name='learning_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea'),
        ),
        migrations.AddField(
            model_name='projectrubric',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.strand'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.strand'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='learning_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea'),
        ),
        migrations.AddField(
            model_name='classactivitie',
            name='learning_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea'),
        ),
        migrations.AddField(
            model_name='classactivitie',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.strand'),
        ),
        migrations.AddField(
            model_name='classactivitie',
            name='sub_strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.sub_strand'),
        ),
        migrations.AddField(
            model_name='authenticassessmentrubric',
            name='learning_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea'),
        ),
        migrations.AddField(
            model_name='authenticassessmentrubric',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_info.strand'),
        ),
        migrations.AddField(
            model_name='authenticassessment',
            name='learning_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.learningarea'),
        ),
        migrations.AddField(
            model_name='authenticassessment',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.strand'),
        ),
        migrations.AddField(
            model_name='authenticassessment',
            name='sub_strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_info.sub_strand'),
        ),
        migrations.AddField(
            model_name='authenticassessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
