# Generated by Django 4.2.4 on 2023-10-17 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticassessment',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 25, 49, 703510, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='authenticassessmentrubric',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 25, 49, 707506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='classactivitie',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 25, 49, 702512, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='summativeassessment',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 25, 49, 704509, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='writtentest',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 17, 22, 25, 49, 704509, tzinfo=datetime.timezone.utc)),
        ),
    ]
