# Generated by Django 4.2.4 on 2023-10-19 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0004_alter_authenticassessment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticassessment',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 19, 15, 34, 24, 385706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='authenticassessmentrubric',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 19, 15, 34, 24, 388704, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='classactivitie',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 19, 15, 34, 24, 385706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='summativeassessment',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 19, 15, 34, 24, 386706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='writtentest',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 19, 15, 34, 24, 386706, tzinfo=datetime.timezone.utc)),
        ),
    ]
